// export const FETCH_CART_REQUEST = "FETCH_CART_REQUEST";
// export const FETCH_CART_SUCCESS = "FETCH_CART_SUCCESS";
// export const FETCH_CART_FAILURE = "FETCH_CART_FAILURE";

// export const UPDATE_CART_ITEM_REQUEST = "UPDATE_CART_ITEM_REQUEST";
// export const UPDATE_CART_ITEM_SUCCESS = "UPDATE_CART_ITEM_SUCCESS";
// export const UPDATE_CART_ITEM_FAILURE = "UPDATE_CART_ITEM_FAILURE";

// export const EMPTY_CART_REQUEST = "EMPTY_CART_REQUEST";
// export const EMPTY_CART_SUCCESS = "EMPTY_CART_SUCCESS";
// export const EMPTY_CART_FAILURE = "EMPTY_CART_FAILURE";